logging:
  level:
    org.flywaydb.core: DEBUG
    com.your.package: DEBUG
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1



  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Serega9900
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082

weather:
  api:
    baseUrl: https://api.openweathermap.org
    key: 7a5864eb5cac7c74e9bc2a2e3a5023bf

