logging:
  level:
    org.flywaydb.core: DEBUG
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1



  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Serega9900
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8082

