spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: Serega9900
    hikari:
      connection-init-sql: SET search_path TO test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  flyway:
    enabled: false